In [ ]:
##https://github.com/kcncell/DeepLearning_BreastCancer_Beginner/blob/main/Cancer_diagnosis_deepLearningProject.ipynb

In [5]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer

In [12]:
data=load_breast_cancer()

In [17]:
df=pd.DataFrame(data=data.data,columns=data.feature_names)

In [18]:
df['target']=data.target

In [19]:
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [20]:
df['target'].unique()

array([0, 1])

In [21]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [22]:
##split independent and dependent variable
X=df.drop(labels='target',axis=1)
y=df['target']

In [23]:
from sklearn.model_selection import train_test_split

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [37]:
from sklearn.preprocessing import MinMaxScaler

In [38]:
Min_max=MinMaxScaler()

In [39]:
X_train=Min_max.fit_transform(X_train)

In [40]:
X_test=Min_max.transform(X_test)

In [29]:
## load tensorflow keras Api

In [30]:
from tensorflow import keras

In [41]:
y_train=keras.utils.to_categorical(y_train,num_classes=2)

In [42]:
y_train[:5]

array([[1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [33]:
X_train.shape

(381, 30)

In [43]:
## create keras model for breast cancer
model=keras.Sequential([
    keras.layers.Dense(100,activation='relu',input_shape=(X_train.shape[1],)),
    keras.layers.Dense(200,activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(2,activation='softmax')
])

In [45]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics='accuracy')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 100)               3100      
                                                                 
 dense_1 (Dense)             (None, 200)               20200     
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_2 (Dense)             (None, 2)                 402       
                                                                 
Total params: 23,702
Trainable params: 23,702
Non-trainable params: 0
_________________________________________________________________


In [46]:
history=model.fit(X_train,y_train,epochs=30,batch_size=30,verbose=2,validation_split=0.3, shuffle=True)

Epoch 1/30
9/9 - 2s - loss: 0.6389 - accuracy: 0.6391 - val_loss: 0.5957 - val_accuracy: 0.8609 - 2s/epoch - 243ms/step
Epoch 2/30
9/9 - 0s - loss: 0.5422 - accuracy: 0.8609 - val_loss: 0.4987 - val_accuracy: 0.8783 - 98ms/epoch - 11ms/step
Epoch 3/30
9/9 - 0s - loss: 0.4314 - accuracy: 0.8910 - val_loss: 0.3952 - val_accuracy: 0.8783 - 103ms/epoch - 11ms/step
Epoch 4/30
9/9 - 0s - loss: 0.3345 - accuracy: 0.8947 - val_loss: 0.3267 - val_accuracy: 0.8870 - 95ms/epoch - 11ms/step
Epoch 5/30
9/9 - 0s - loss: 0.2948 - accuracy: 0.8722 - val_loss: 0.2746 - val_accuracy: 0.8957 - 98ms/epoch - 11ms/step
Epoch 6/30
9/9 - 0s - loss: 0.2551 - accuracy: 0.8872 - val_loss: 0.2536 - val_accuracy: 0.8957 - 95ms/epoch - 11ms/step
Epoch 7/30
9/9 - 0s - loss: 0.2170 - accuracy: 0.9023 - val_loss: 0.2375 - val_accuracy: 0.8957 - 99ms/epoch - 11ms/step
Epoch 8/30
9/9 - 0s - loss: 0.2025 - accuracy: 0.9060 - val_loss: 0.2154 - val_accuracy: 0.9043 - 97ms/epoch - 11ms/step
Epoch 9/30
9/9 - 0s - loss: 0.19

In [49]:
y_pred=model.predict(X_test)

6/6 [==============================] - 0s 5ms/step


In [51]:
y_pred[:5]

array([[1.6396320e-01, 8.3603686e-01],
       [9.9987113e-01, 1.2888944e-04],
       [9.9771631e-01, 2.2837692e-03],
       [7.4022624e-04, 9.9925977e-01],
       [5.3469138e-04, 9.9946529e-01]], dtype=float32)

In [56]:
y_pred= [np.argmax(i) for i in y_pred]

In [57]:
y_pred[:5]

[1, 0, 0, 1, 1]

In [58]:
y_test[:5]

204    1
70     0
131    0
431    1
540    1
Name: target, dtype: int32

In [63]:
from sklearn.metrics import  confusion_matrix,accuracy_score

In [64]:
ac=accuracy_score(y_test,y_pred)
cf=confusion_matrix(y_test,y_pred)

In [65]:
print("score",ac)
print("confusion matrirc",cf)

score 0.9787234042553191
confusion matrirc [[ 66   1]
 [  3 118]]


In [ ]:
fig = plt.subplots(figsize = (5,5))
fig = sns.heatmap(cf, annot=True, fmt='d',xticklabels=('cancer','No-cancer'), yticklabels=('cancer', 'No-cancer'), cmap='Blues',)
fig.set_title('Confusion Matrix', fontsize=14)
fig.set_xlabel('Predicted', fontsize=14)
fig.set_ylabel('Actual',fontsize=14)