#### Part -1

In [62]:
import numpy as np

In [153]:
ls=[1,2,3,4,5]
type(ls)

list

In [7]:
arr=np.array(ls)
arr

array([1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [13]:
arr2=np.array([[1,2,3],[4,5,6]])

In [14]:
arr2.ndim

2

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
mat=np.matrix(ls)

In [17]:
mat

matrix([[1, 2, 3, 4, 5]])

In [22]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [23]:
arr

array([1, 2, 3, 4, 5])

In [24]:
arr[0]=12

In [25]:
a=arr

In [26]:
a

array([12,  2,  3,  4,  5])

In [27]:
arr[1]=20

In [29]:
a
## in this case both values are changes in a and arr

array([12, 20,  3,  4,  5])

In [33]:
b=np.copy(arr)

In [34]:
b

array([12, 20,  3,  4,  5])

In [35]:
arr[0]=100

In [36]:
arr

array([100,  20,   3,   4,   5])

In [37]:
b

array([12, 20,  3,  4,  5])

In [38]:
np.fromfunction(lambda i,j : i==j,(2,2))

array([[ True, False],
       [False,  True]])

In [42]:
np.fromfunction(lambda i,j : i*10,(2,2))

array([[ 0.,  0.],
       [10., 10.]])

In [45]:
list(i*i for i in range(0,5))

[0, 1, 4, 9, 16]

In [46]:
iterable=(i*i for i in range(0,5))

In [47]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [49]:
np.fromstring('23 34 45',sep= ' ')

array([23., 34., 45.])

In [50]:
np.fromstring('23.34.45',sep= '.')

array([23.34, 45.  ])

In [53]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
arr2.ndim

2

In [55]:
arr2.size

6

In [57]:
arr2.shape

(2, 3)

In [61]:
arr2.dtype

dtype('int32')

### Part-2

In [64]:
list(range(5))

[0, 1, 2, 3, 4]

In [65]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [66]:
list(range(0.4,10.4,0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [67]:
np.arange(0.1,1,0.1)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [68]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [69]:
np.logspace(0,10,10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [70]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [80]:
np.zeros((2,2,1))

array([[[0.],
        [0.]],

       [[0.],
        [0.]]])

In [79]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [82]:
ze=np.zeros((3,3))

In [84]:
ze.size

9

In [85]:
ze.shape

(3, 3)

In [87]:
on=np.ones((3,2))

In [89]:
on+4

array([[5., 5.],
       [5., 5.],
       [5., 5.]])

In [90]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [91]:
import pandas as pd

In [94]:
arr2=np.eye(5)

In [95]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [98]:
pd.DataFrame(arr2, columns=['a','b','c','d','e'])

a    b    c    d    e
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [99]:
np.random.rand(2,1)

array([[0.27557371],
       [0.27888013]])

In [100]:
np.random.randn(2,1)

array([[-0.91073702],
       [-0.00671906]])

In [106]:
arr3=np.random.randint(1,4,(4,2))

In [107]:
arr3

array([[2, 3],
       [3, 1],
       [3, 2],
       [3, 1]])

In [108]:
arr3.shape

(4, 2)

In [110]:
arr3.reshape(2,4)

array([[2, 3, 3, 1],
       [3, 2, 3, 1]])

In [111]:
arr3.reshape(4,2)

array([[2, 3],
       [3, 1],
       [3, 2],
       [3, 1]])

In [ ]:
art

In [17]:
arr1=np.random.randint(1,10,(2,5))

In [18]:
arr1

array([[4, 6, 3, 2, 5],
       [4, 2, 9, 9, 7]])

In [20]:
arr1>5

array([[False,  True, False, False, False],
       [False, False,  True,  True,  True]])

In [21]:
arr1[arr1>5]

array([6, 9, 9, 7])

In [27]:
arr1[0:1,0:2]

array([[4, 6]])

In [29]:
arr1[0][1:3]

array([6, 3])

In [30]:
a5=np.random.randint(1,10,(5,6))

In [31]:
a5

array([[2, 8, 5, 6, 5, 9],
       [3, 1, 2, 9, 7, 5],
       [7, 4, 2, 6, 8, 6],
       [4, 6, 3, 2, 8, 8],
       [9, 4, 7, 7, 1, 3]])

In [35]:
a5[0][1:3]

array([8, 5])

In [36]:
a5[2:4,(4,5)]

array([[8, 6],
       [8, 8]])

In [37]:
arr8=np.random.randint(1,3,(3,3))
arr9=np.random.randint(1,3,(3,3))

In [38]:
arr8

array([[2, 2, 1],
       [1, 1, 2],
       [2, 1, 2]])

In [39]:
arr9

array([[2, 2, 2],
       [1, 1, 2],
       [2, 2, 2]])

In [42]:

##index based add/multi
arr8+arr9

array([[4, 4, 3],
       [2, 2, 4],
       [4, 3, 4]])

In [41]:
arr8*arr9

array([[4, 4, 2],
       [1, 1, 4],
       [4, 2, 4]])

## matrix based multiplication

In [67]:
arr1=np.array([[2,2,1],[1,1,1],[1,2,2]])

In [72]:
arr2=np.array([[[1,2,2],[1,2,1],[2,1,1]]])

In [64]:
np.random.randint(1,2,(3,3))

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [69]:
arr1.shape

(3, 3)

In [73]:
np.multiply(arr1,arr2)

array([[[2, 4, 2],
        [1, 2, 1],
        [2, 2, 2]]])

In [74]:
arr1 @ arr2

array([[[6, 9, 7],
        [4, 5, 4],
        [7, 8, 6]]])

In [81]:
art=np.array([[1,2,3,4]])
art

array([[1, 2, 3, 4]])

In [82]:
art.shape

(1, 4)

In [83]:
b=art.T

In [84]:
b.shape

(4, 1)

In [85]:
b

array([[1],
       [2],
       [3],
       [4]])

## Part-3

In [86]:
import numpy as np

In [113]:
### array manipulation
arr=np.random.randint(1,10,(4,4))
arr

array([[1, 7, 1, 9],
       [5, 9, 5, 1],
       [6, 9, 2, 3],
       [5, 5, 5, 8]])

In [116]:
arr[2:4,(2,3)]

array([[2, 3],
       [5, 8]])

In [120]:
arr1=arr.reshape(2,8)

In [121]:
arr1

array([[1, 7, 1, 9, 5, 9, 5, 1],
       [6, 9, 2, 3, 5, 5, 5, 8]])

In [122]:
arr1.T

array([[1, 6],
       [7, 9],
       [1, 2],
       [9, 3],
       [5, 5],
       [9, 5],
       [5, 5],
       [1, 8]])

In [123]:
arr

array([[1, 7, 1, 9],
       [5, 9, 5, 1],
       [6, 9, 2, 3],
       [5, 5, 5, 8]])

In [124]:
arr.flatten()

array([1, 7, 1, 9, 5, 9, 5, 1, 6, 9, 2, 3, 5, 5, 5, 8])

In [126]:
sq=np.array([[1],[2],[3]])

In [128]:
sq.squeeze()

array([1, 2, 3])

In [129]:
np.repeat(sq,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [131]:
## diagonal value update
np.diag(np.array([1,2,4,5]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

### numpy string operation

In [134]:
arr=np.array(['mar','eee','eee'])

In [135]:
arr

array(['mar', 'eee', 'eee'], dtype='<U3')

In [136]:
np.char.upper(arr)

array(['MAR', 'EEE', 'EEE'], dtype='<U3')

In [137]:
np.char.capitalize(arr)

array(['Mar', 'Eee', 'Eee'], dtype='<U3')

In [138]:
np.char.title(arr)

array(['Mar', 'Eee', 'Eee'], dtype='<U3')

In [141]:
arr1.reshape(4,4)


array([[1, 7, 1, 9],
       [5, 9, 5, 1],
       [6, 9, 2, 3],
       [5, 5, 5, 8]])

## mathematical operation

In [143]:
np.sin(arr1)

array([[ 0.84147098,  0.6569866 ,  0.84147098,  0.41211849, -0.95892427,
         0.41211849, -0.95892427,  0.84147098],
       [-0.2794155 ,  0.41211849,  0.90929743,  0.14112001, -0.95892427,
        -0.95892427, -0.95892427,  0.98935825]])

In [144]:
np.cos(arr1)

array([[ 0.54030231,  0.75390225,  0.54030231, -0.91113026,  0.28366219,
        -0.91113026,  0.28366219,  0.54030231],
       [ 0.96017029, -0.91113026, -0.41614684, -0.9899925 ,  0.28366219,
         0.28366219,  0.28366219, -0.14550003]])

In [145]:
np.log(arr1)

array([[0.        , 1.94591015, 0.        , 2.19722458, 1.60943791,
        2.19722458, 1.60943791, 0.        ],
       [1.79175947, 2.19722458, 0.69314718, 1.09861229, 1.60943791,
        1.60943791, 1.60943791, 2.07944154]])

In [146]:
np.power(arr1,2)

array([[ 1, 49,  1, 81, 25, 81, 25,  1],
       [36, 81,  4,  9, 25, 25, 25, 64]], dtype=int32)

In [147]:
np.mean(arr1)

5.0625

In [149]:
np.median(arr1)

5.0

In [151]:
np.std(arr1)

2.7719296076920856

In [152]:
arr1.std()

2.7719296076920856

## part -4 (sort, search and counting function)

In [154]:
import numpy as  np

In [167]:
arr=np.array([1,2,3,3,3])
arr1=np.array([1,2,3,3,3])

In [156]:
arr.byteswap()

array([16777216, 33554432, 50331648])

In [165]:
np.argsort(arr)

array([0, 1, 2, 3, 4], dtype=int64)

In [166]:
np.flip(arr)

array([3, 3, 3, 2, 1])

In [ ]:
np.concatenate(arr,arr1)

In [169]:
np.unique(arr)

array([1, 2, 3])

In [170]:
arr=np.array([2,3,4,5])

In [174]:
np.sort(arr)

array([2, 3, 4, 5])

In [180]:
arrs=np.array([2,390,4,5,789])

In [181]:
np.sort(arrs)

array([  2,   4,   5, 390, 789])

In [189]:
np.searchsorted(arrs,900)

5

In [190]:
ar=np.array([0,0,0,1,2,3,4])

In [191]:
np.count_nonzero(ar)

4

In [194]:
np.where(ar>0)

(array([3, 4, 5, 6], dtype=int64),)

In [195]:
arrs

array([  2, 390,   4,   5, 789])

In [196]:
np.extract(arrs >5 ,arrs)

array([390, 789])

In [197]:
arrs.byteswap()

array([   33554432, -2046754816,    67108864,    83886080,   352518144])

In [198]:
arrs

array([  2, 390,   4,   5, 789])

In [199]:
##copy and views

In [200]:
a=np.array([1,2,3])

In [204]:
b=np.copy(a)

In [202]:
b

array([1, 2, 3])

In [205]:
c=a.view()

In [206]:
c

array([1, 2, 3])

## matrix

In [207]:
import numpy.matlib as nm

In [208]:
nm.zeros(1)

matrix([[0.]])

In [211]:
nm.ones((2,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [212]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])