In [2]:
import tensorflow as tf

## Constant

In [4]:
cons=tf.constant(42)
cons

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
cons.numpy()

42

In [9]:
con_init=tf.constant(1,dtype=tf.int64)
con_init

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [10]:
con_init.numpy()

1

In [11]:
con_init=tf.constant([[2,2],[4,5]])
con_init

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [4, 5]])>

In [16]:
con_init.numpy()[1][1]

5

In [17]:
con_init.dtype

tf.int32

## generaet the zeros and ones

In [18]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [19]:
## multiple function

In [23]:
cons1=tf.constant([[1,2,3],[4,5,6]])
cons2=tf.constant([[6,7,8],[9,10,11]])
result=tf.add(cons1,cons2)
result

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  9, 11],
       [13, 15, 17]])>

## Random constant

In [24]:
tf.random.normal(shape=(2,2),mean=0,stddev=0.1)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.07680674,  0.10144116],
       [ 0.03545678, -0.06576454]], dtype=float32)>

In [26]:
tf.random.uniform(shape=(2,2),minval=0,maxval=10,dtype=tf.int64)

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[6, 3],
       [4, 9]], dtype=int64)>

### Variables

In [30]:
var0=23
var1=tf.Variable(45)
var0,var1.numpy()

(23, 45)

## Ranking

In [33]:
cons=tf.constant([[1,2,3],[4,5,6]])
tf.rank(cons).numpy()

2

In [32]:
cons.shape

TensorShape([2, 3])

In [34]:
cons.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
tf.size([[1, 2, 3],
       [4, 5, 6]]).numpy()

6

In [37]:
cons1=tf.constant([[1,2,3],[4,5,6]])
cons2=tf.constant([[6,7,8],[9,10,11]])
result=tf.add(cons1,cons2)
tf.square(result)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 49,  81, 121],
       [169, 225, 289]])>

### Data type

In [39]:
a=10


In [41]:
type(a)

int

In [45]:
b=tf.cast(a,dtype=tf.float16)

In [46]:
b

<tf.Tensor: shape=(), dtype=float16, numpy=10.0>

In [47]:
varx=[3,4,5,6]
vary=5
varz=tf.math.squared_difference(varx,vary)
varz

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 1, 0, 1])>

## mean 

In [50]:
num=[1,2,4,5,6]
data=tf.reduce_mean(num)
data

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [56]:
num=tf.constant([[1,2,4,5,6],[3,4,5,6,7]],dtype=tf.float16)
data=tf.reduce_mean(num,axis=0)
data

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([2. , 3. , 4.5, 5.5, 6.5], dtype=float16)>

## example of dice

In [64]:
dice1=tf.random.uniform(shape=[6,1],minval=1,maxval=6,dtype=tf.int32)
dice2=tf.random.uniform(shape=[6,1],minval=1,maxval=6,dtype=tf.int32)
dice_sum=dice1+dice2

result=tf.concat([dice1,dice2,dice_sum],axis=1)
result

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[5, 2, 7],
       [2, 1, 3],
       [2, 4, 6],
       [1, 4, 5],
       [2, 2, 4],
       [4, 4, 8]])>

In [71]:
tf5=tf.constant([3,4,5,6,7,8,9])
resu=tf.argmax(tf5)
tf5[resu.numpy()].numpy()

9

In [72]:
from datetime import datetime

In [75]:
datetime.now().strftime("%y_%m_%d")

'23_06_11'

## Saving and restoring the values

In [84]:
varible=tf.Variable([2,3,4])
checkpoint=tf.train.Checkpoint(var=varible)
savepath=checkpoint.save('./vars')

In [87]:
checkpoint.restore(savepath)

## Gradient Decent

In [88]:
a=tf.random.uniform(shape=(2,2))
b=tf.random.uniform(shape=(2,2))

In [89]:
with tf.GradientTape() as tape:
    tape.watch(a)
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da=tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.8662174  0.3121996 ]
 [0.04481037 0.80714464]], shape=(2, 2), dtype=float32)


In [92]:
a=tf.Variable(a)
with tf.GradientTape() as tape:
    c=tf.sqrt(tf.square(a)+tf.square(b))
    dc_da=tape.gradient(c,a)
    print(dc_da)

tf.Tensor(
[[0.8662174  0.3121996 ]
 [0.04481037 0.80714464]], shape=(2, 2), dtype=float32)
