#### 1. What are the different data structures used in Tensorflow?. Give some examples
- Variable
- data
- Constant

In [1]:
import tensorflow as tf

In [4]:
a=tf.constant(23)
b=tf.Variable(34)
input_data = [[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
dataset = tf.data.Dataset.from_tensor_slices(input_data)
print(a)
print(b)
print(dataset)

tf.Tensor(23, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=34>
<_TensorSliceDataset element_spec=TensorSpec(shape=(2,), dtype=tf.int32, name=None)>


#### How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example
- Constants hold fixed values that cannot be changed, while variables are mutable and can be updated.

In [5]:
con=tf.constant(3)
var=tf.Variable(45)

In [9]:
con
##contand don't have any assign function

45

In [10]:
var.assign(34)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=34>

### 3.Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.

In [13]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result_add = tf.add(matrix_a, matrix_b)
print("Matrix Addition Result:")
print(result_add.numpy())

# Matrix addition using +
result_add_op = matrix_a + matrix_b
print("Matrix Addition Result (Op):")
print(result_add_op.numpy())

Matrix Addition Result:
[[ 6  8]
 [10 12]]
Matrix Addition Result (Op):
[[ 6  8]
 [10 12]]


In [14]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result_add = tf.matmul(matrix_a, matrix_b)
print("Matrix Addition Result:")
print(result_add.numpy())

# Matrix addition using +
result_add_op = matrix_a * matrix_b
print("Matrix Addition Result (Op):")
print(result_add_op.numpy())

Matrix Addition Result:
[[19 22]
 [43 50]]
Matrix Addition Result (Op):
[[ 5 12]
 [21 32]]


In [19]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
# Matrix  elementwise
result_add_op = matrix_a + matrix_b
result_div_op = matrix_a - matrix_b
result_mul_op = matrix_a * matrix_b
result_div_op = matrix_a / matrix_b
print("add",result_add_op.numpy())
print("div",result_div_op.numpy())
print("mul",result_mul_op.numpy())
print("div",result_div_op.numpy())

add [[ 6  8]
 [10 12]]
div [[0.2        0.33333333]
 [0.42857143 0.5       ]]
mul [[ 5 12]
 [21 32]]
div [[0.2        0.33333333]
 [0.42857143 0.5       ]]


#### 4. Create a normal matrix A with dimensions 4x4, using TensorFlow's random_normal function. Display the values of matrix A

In [70]:
matirx_a=tf.random.normal(shape=(4,4))
matirx_a

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-1.7376856 ,  0.607164  ,  0.85498244,  0.600156  ],
       [-1.054437  ,  0.6212021 ,  1.4448001 ,  0.76276124],
       [ 0.7136727 , -1.150614  ,  1.7849942 , -0.9582446 ],
       [ 0.70901346, -0.44178343,  0.24696025, -1.8348274 ]],
      dtype=float32)>

#### 5. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix b

In [71]:
matrix_b=tf.random.truncated_normal(shape=(4,4))
print(matrix_b.numpy())

[[-1.1568284   1.234316   -1.3926697   0.5871198 ]
 [ 1.4279202  -0.20630702  1.6364379   0.2568684 ]
 [ 0.72015476 -0.09620837 -1.1391588   1.0138958 ]
 [ 0.25406006 -0.79838896  1.0643198  -0.28188702]]


#### 6.Create a matrix C with dimensions 4x4, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C

In [77]:
matrix_c=tf.random.normal(shape=(4,4),mean=3,stddev=0.5)
matrix_c.numpy()

array([[3.4454095, 2.203536 , 3.6716542, 3.2304246],
       [3.003105 , 2.6989632, 2.5642197, 2.768471 ],
       [3.8363087, 3.005832 , 3.9116333, 3.4919682],
       [3.5361207, 2.8015425, 3.0866156, 3.3784688]], dtype=float32)

### 7. Perform matrix addition between matrix A and matrix B, and store the result in matrix D

In [78]:
matrix_d= tf.add(matirx_a,matrix_b)
matrix_d

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-2.894514  ,  1.84148   , -0.53768724,  1.1872759 ],
       [ 0.37348318,  0.4148951 ,  3.081238  ,  1.0196296 ],
       [ 1.4338274 , -1.2468224 ,  0.6458354 ,  0.05565113],
       [ 0.9630735 , -1.2401724 ,  1.3112801 , -2.1167145 ]],
      dtype=float32)>

#### 8.Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [79]:
matrix_d= tf.multiply(matrix_c,matrix_d)
matrix_d

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[-9.972787  ,  4.0577674 , -1.9742017 ,  3.8354053 ],
       [ 1.1216092 ,  1.1197865 ,  7.9009714 ,  2.822815  ],
       [ 5.5006046 , -3.7477386 ,  2.5262713 ,  0.19433197],
       [ 3.405544  , -3.4743958 ,  4.0474176 , -7.1512537 ]],
      dtype=float32)>

- 1.Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function
- 2.Calculate the transpose of matrix F and store the result in matrix G
- 3.Calculate the elementDwise exponential of matrix F and store the result in matrix H
- 4.Create a matrix I by concatenating matrix F and matrix G horizontally
- 5.Create a matrix J by concatenating matrix F and matrix H vertically.

In [62]:
matrix_f=tf.random.uniform(shape=(2,2),minval=0,maxval=6)
matrix_f

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.39829516, 4.5055666 ],
       [1.9967251 , 1.8893516 ]], dtype=float32)>

In [63]:
matrix_g=tf.transpose(matrix_f)
matrix_g

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.39829516, 1.9967251 ],
       [4.5055666 , 1.8893516 ]], dtype=float32)>

In [64]:
matrix_h=tf.exp(matrix_f)
matrix_h

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4892836, 90.519615 ],
       [ 7.3648973,  6.615078 ]], dtype=float32)>

In [65]:
matrix_i=tf.concat([matrix_f,matrix_g],axis=1)
matrix_i

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[0.39829516, 4.5055666 , 0.39829516, 1.9967251 ],
       [1.9967251 , 1.8893516 , 4.5055666 , 1.8893516 ]], dtype=float32)>

In [66]:
matrix_j=tf.concat([matrix_f,matrix_h],axis=1)
matrix_j

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.39829516,  4.5055666 ,  1.4892836 , 90.519615  ],
       [ 1.9967251 ,  1.8893516 ,  7.3648973 ,  6.615078  ]],
      dtype=float32)>