## Logistic Regression

In [1]:
from sklearn.datasets import load_iris

In [2]:
dataset=load_iris()

In [ ]:
print(dataset.DESCR)

In [6]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [7]:
import pandas as pd
import numpy as np

In [8]:
df=pd.DataFrame(dataset.data , columns=dataset.feature_names)

In [9]:
df['target']=dataset.target

In [11]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [14]:
df_copy=df[df['target']!=2]

In [20]:
df_copy['target'].unique()

array([0, 1])

In [18]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  100 non-null    float64
 1   sepal width (cm)   100 non-null    float64
 2   petal length (cm)  100 non-null    float64
 3   petal width (cm)   100 non-null    float64
 4   target             100 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 4.3 KB


In [46]:
## independent and dependent feature
X=df_copy.iloc[:,:-1]
y=df_copy.iloc[:,-1]

In [48]:
## train the model
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.20)

In [54]:
X_train.shape,y_train.shape

((80, 4), (80,))

In [61]:
X_test.shape,y_test.shape

((20, 4), (20,))

In [56]:
## train the model
from sklearn.linear_model import LogisticRegression

In [75]:
classification=LogisticRegression()

In [76]:
classification.fit(X_train,y_train)

LogisticRegression()

In [80]:
y_pred=classification.predict(X_test)

In [81]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0])

## Confusion Matrix ,Accuracy, precision, recall, classfication report

In [82]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,classification_report

In [83]:
print("confusion matrix", confusion_matrix(y_test, y_pred))

confusion matrix [[12  0]
 [ 0  8]]


In [84]:
print("accuracy_score", accuracy_score(y_test, y_pred))

accuracy_score 1.0


In [85]:
print("precision_score", precision_score(y_test, y_pred))

precision_score 1.0


print("recall_score", recall_score(y_test, y_pred))

In [89]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      1.00      1.00         8

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



## cross validation

In [90]:
from sklearn.model_selection import KFold

In [92]:
cv=KFold(n_splits=5,shuffle=True)

In [93]:
cv

KFold(n_splits=5, random_state=None, shuffle=True)

In [94]:
from sklearn.model_selection import cross_val_score

In [98]:
## These are the score for cross validation
score=cross_val_score(classification,X_train,y_train,scoring='accuracy',cv=cv)
score

array([1., 1., 1., 1., 1.])

In [99]:
np.mean(score)

1.0

In [100]:
## Take more complex data and perfoemm the logistic regression
from sklearn.datasets import make_classification

In [101]:
x,y=make_classification(n_samples=1000,n_features=10,n_informative=5,n_classes=3,random_state=1)

In [ ]:
x

In [ ]:
y

In [105]:
X_train,X_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.20)

In [106]:
complex_clas=LogisticRegression(max_iter=100)

In [107]:
complex_clas.fit(X_train,y_train)

LogisticRegression()

In [113]:
y_test

array([1, 2, 2, 0, 1, 0, 1, 2, 1, 2, 0, 0, 2, 2, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 2, 2, 0, 1, 2, 1, 0, 0,
       2, 0, 0, 1, 2, 0, 1, 1, 0, 2, 2, 2, 0, 0, 2, 1, 0, 2, 1, 2, 2, 1,
       1, 2, 0, 0, 1, 2, 1, 1, 1, 1, 0, 2, 2, 2, 0, 1, 0, 2, 2, 2, 1, 2,
       1, 2, 1, 0, 2, 2, 2, 0, 1, 1, 0, 0, 2, 0, 0, 1, 0, 2, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 0, 2, 2, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 2, 2, 2, 1, 2, 0, 0, 0, 2, 2, 2, 2, 1, 1, 2,
       2, 1, 2, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 2, 2, 0, 1, 1, 0, 0, 0, 0,
       1, 2, 2, 1, 0, 2, 1, 0, 1, 0, 1, 0, 1, 2, 0, 1, 1, 2, 2, 1, 0, 1,
       0, 1])

In [114]:
y_pred_comp=complex_clas.predict(X_test)
y_pred_comp

array([1, 0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 0, 0, 2, 2, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 2, 2, 2, 1, 0, 0, 2, 2, 0, 2, 0, 0, 1, 0, 0, 2, 0,
       2, 0, 2, 1, 0, 0, 1, 1, 0, 2, 0, 2, 1, 0, 2, 1, 0, 1, 2, 2, 0, 2,
       1, 1, 1, 0, 1, 2, 1, 1, 1, 2, 0, 2, 0, 2, 0, 1, 0, 2, 1, 0, 1, 2,
       1, 1, 1, 0, 2, 2, 2, 0, 0, 2, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 2, 1,
       2, 1, 1, 0, 1, 2, 2, 0, 0, 0, 2, 1, 1, 0, 2, 0, 2, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 2, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2,
       2, 1, 2, 1, 0, 1, 1, 0, 2, 1, 1, 2, 1, 0, 0, 0, 1, 2, 0, 0, 0, 0,
       1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 2, 1, 1, 1, 2, 0, 1, 0, 0,
       0, 1])

In [112]:
print("confusion matrix", confusion_matrix(y_test, y_pred_comp))
print("accuracy_score", accuracy_score(y_test, y_pred_comp))
print(classification_report(y_test, y_pred_comp))

confusion matrix [[59  5  4]
 [ 9 51 11]
 [21  9 31]]
accuracy_score 0.705
              precision    recall  f1-score   support

           0       0.66      0.87      0.75        68
           1       0.78      0.72      0.75        71
           2       0.67      0.51      0.58        61

    accuracy                           0.70       200
   macro avg       0.71      0.70      0.69       200
weighted avg       0.71      0.70      0.70       200



In [115]:
## cross validation
cv=KFold(n_splits=5,shuffle=True)

In [116]:
score=cross_val_score(complex_clas,X_train,y_train,scoring='accuracy',cv=cv)
score

array([0.68125, 0.68125, 0.65625, 0.6875 , 0.65625])

In [117]:
np.mean(score)

0.6725